apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: prod
  namespace: prod
spec:
  baseDomain: arencloud.com
  clusterName: prod
  controlPlaneConfig:
    servingCertificates: {}
  installed: false
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    # aci == AgentClusterInstall
    name: prod
    version: v1beta1
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster-name: "prod"
  pullSecretRef:
    name: pull-secret