apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: prod
  namespace: prod
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  #  proxy:
  #    httpProxy: <proxy>
  #    httpsProxy: <proxy>
  #    noProxy: <domain-or-ips-comma-sepparated>
  #  additionalNTPSources:
  #    - 0.rhel.pool.ntp.org
  clusterRef:
    name: prod
    namespace: prod
  sshAuthorizedKey: '$(SSHPUBKEY)'
  agentLabelSelector:
    matchLabels:
      cluster-name: prod
  pullSecretRef:
    name: pull-secret
  nmStateConfigLabelSelector:
    matchLabels:
      cluster-name: prod
# User for modify ignition during discovery
#  ignitionConfigOverride: ''