---

- name: remove virtual machines
  community.libvirt.virt:
    name: "{{ vmname }}-{{ item }}"
    state: shutdown
    command: destroy
    force: true
  when: count is defined
  loop: "{{ range(0, count)|list }}"

- name: remove virtual machine
  community.libvirt.virt:
    name: "{{ vmname }}"
    state: shutdown
    command: destroy
    force: true
  when: count is undefined