---
- name: vm info
  community.libvirt.virt:
    name: "{{ vmname }}"
    command: get_xml
  register: running_vms

- name: print vm
  ansible.builtin.debug:
    msg: "{{ running_vms.get_xml | xml_to_json }}"